# Generated by Django 3.1.1 on 2020-10-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('texto', models.TextField()),
                ('area_Da_Empresa', models.CharField(max_length=30)),
            ],
        ),
    ]
