# Generated by Django 3.1.1 on 2020-10-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCaixaSugestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mensagemArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=100)),
                ('resposta', models.TextField()),
                ('sugestionador', models.CharField(max_length=100)),
            ],
        ),
    ]
